name: Deploy Backend (Render)

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env: { RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }} }
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "Missing secret: RENDER_DEPLOY_HOOK"; exit 1
          fi
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"
          echo "Render deploy triggered."
