name: Backend • Test

on:
  push:
    branches: [ "main" ]
    paths: [ "backend/**", ".github/workflows/backend-test.yml" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "backend/**" ]

permissions: { contents: read }

jobs:
  test:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: backend } }
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET:  ${{ secrets.JWT_SECRET }}
      NODE_ENV:    ${{ secrets.NODE_ENV }}
      PORT:        ${{ secrets.PORT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - run: npm ci
      - name: Unit tests
        run: npm test --if-present -- --passWithNoTests
